---
title: "Career stages"
output: html_notebook
---


- 3 groups:

- junior: up to 5
- early: between 5 and 10
- Mid: between 10 + (no more than 16)



```{r setup}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
library(tidyverse)
```


```{r}
colsn <- 
c('Researcher_id','first_year','active_years','pub_year','pub_id','country_code',
  'author_seq','is_corresponding_author','cluster_id1','LR_main_field')

df <- read_delim('../../data/CS_individuals_jun23.csv',delim = ';',col_names = colsn)
```


```{r}

# df_careers <- df %>%
#   mutate(career_age = pub_year - first_year,
#          career_stage = case_when(career_age<=5 ~ 'junior' ,
#                                   between(career_age,6,10) ~ 'early',
#                                   career_age>10 ~'middle'))

```

```{r}
# df_careers %>% 
#   group_by(career_stage) %>% 
#   summarise(n_author=length(unique(Researcher_id)))

```


```{r}
# df_careers %>% 
#   group_by(career_stage) %>% 
#   summarise(n_papers=length(unique(pub_id)))

```

cases where we don't have any paper for the first year of publication


```{r}
country_origin_simple <-
  df %>% 
  filter(first_year==pub_year) %>% 
  group_by(Researcher_id) %>% 
  summarise(country_code = unique(country_code),
            ncountry=length(country_code)) %>% 
  filter(ncountry == 1) %>% 
  mutate(country_origin = country_code) %>% 
  select(-country_code, -ncountry)

df_first_year <- df %>% 
  filter(pub_year==first_year, 
         !Researcher_id %in% country_origin_simple$Researcher_id) %>% 
  group_by(Researcher_id) %>% 
  summarise(first_countries = paste0(unique(country_code),collapse ='-'))

country_origin_2 <- 
  df %>% 
  filter(!Researcher_id %in% country_origin_simple$Researcher_id) %>% 
    left_join(df_first_year, by = 'Researcher_id') %>%
    filter(!is.na(first_countries)) %>%
  group_by(Researcher_id,country_code) %>% 
  summarise(ncountry = n(),
            is_in_first_countries = str_detect(string = first_countries,pattern = country_code)) %>% 
    distinct() %>% 
    filter(is_in_first_countries) %>% 
    group_by(Researcher_id) %>% 
    mutate(nmax = max(ncountry)) %>% 
    filter(ncountry == nmax) %>% 
    distinct(Researcher_id, .keep_all = TRUE) %>% 
  select(Researcher_id, country_origin = country_code)

country_origin <- bind_rows(country_origin_simple,country_origin_2)
```

define mobility
We don't need to define the mobility of authors!


```{r}
# df_mobility <- df %>% 
#   left_join(country_origin) %>% 
#   filter(!is.na(country_origin)) %>% 
#     group_by(Researcher_id) %>% 
#   summarise(mobile = sum(country_code!=country_origin)>0)

```


migration: you stop to publish with your country of origin at least one. 

```{r}
# df %>% 
#   left_join(df_mobility) %>% 
#   left_join(country_origin) %>% 
#   filter(mobile) %>% 
#   mutate(is_country_origin = country_code ==country_origin) %>% 
#   group_by(Researcher_id,pub_year) %>% 
#   summarise(country_seq = paste0(country_code, collapse = '-'),
#          migrated = str_detect(country_seq,country_origin,negate=TRUE)) %>% 
#   distinct() %>% 
#   arrange(Researcher_id,pub_year)

```















```{r}
df_mobility <-
  df_careers %>%
  left_join(country_origin, by = 'Researcher_id') %>%
  filter(!is.na(country_code)) %>%
  group_by(Researcher_id) %>% 
  summarise(countries = paste0(unique(country_code), collapse = '-'),
      mobility = case_when(countries==country_origin~'non_mobile',
                   str_detect(string = countries,pattern = '-') &
                   str_detect(string = countries,pattern = country_origin) ~ 'multi_affiliation',
                   str_detect(string = countries,pattern = country_origin,
                              negate=TRUE) ~ 'mobile'
                                 ))

df_mobility <- df_mobility %>% 
  distinct()

df_mobility %>%
  saveRDS('../../data/mobility/researchers_mobility.rds')
df_mobility <- read_rds('../../data/mobility/researchers_mobility.rds')

```

```{r}
df_mobility <- df_mobility
```

```{r}
df %>% 
  filter(Researcher_id=='ur.010000316675.34') %>% 
  arrange(pub_year)
```



```{r}
df_mobility %>%
  saveRDS('../../data/mobility/researchers_mobility.rds')
df_mobility <- read_rds('../../data/mobility/researchers_mobility.rds')

```

```{r}
df_mobility
```










